# Dockerfile for Nginx

# Use the official Nginx image as a base
FROM nginx:alpine

# Copy your custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port Nginx will serve on
EXPOSE 8080